
<div id="sidebar">
        <dl>
           <dt> Want to share? </dt>
			<dd>
			Found something interesting that would elicit a wow from others? Now multiply the joy and share it 
			with the world!  </dd>
            

          <dt> Add Multiple images </dt>
			<dd>You can click on Add images and select multiple images from your computer</dd>

            <dt> Website </dt>
            <dd> You can add multiple websites for this post. Simply type the website address and click on Add button
                or press Enter key. You can add as many websites as you like. </dd>
            <dt> Groups </dt>
			<dd> Groups help you organize your posts and allows others to find your post quickly.</dd>

        </dl>

</div>

