
<div id="sidebar">
     <div class="section1">
         <h4 class="faded-text b"> Where are the images and websites I just added?</h4>
            <p class="mt10">
            just scroll down to the end of form to see your images and websites. You can also
            click  "show images and websites" link.
            </p>
    </div>
    
    <div class="section">
         <h4 class="faded-text b"> How to add multiple images?</h4>
            <p class="mt10">
            Absolutely. Click the Upload Images button and select multiple images from 
            your computer.
            </p>
    </div>
    
     <div class="section">
         <h4 class="faded-text b"> How to add multiple websites?</h4>
            <p class="mt10">
            Type a website address and click on Add. To add another website, repeat the process.
            </p>
    </div>
    
        
     <div class="section">
         <h4 class="faded-text b"> What are groups?</h4>
            <p class="mt10">
            Groups are like keywords that help you organize your posts and allows others to find your post quickly
            </p>
    </div>
    
</div>

