set ts=4
set shiftwidth=4
set expandtab 
"set nu
"highlight search
set hlsearch

syntax on
filetype plugin indent on
"detect custom file types
au BufNewFile,BufRead *.inc set filetype=php
au BufNewFile,BufRead *.tmpl set filetype=php

" get rid of swp files in working dir
"
set backupdir=/home/rjha/nuke/swap
set backup
set directory=/home/rjha/nuke/swap

" get rid of toolbar
" behave like mswin
set guioptions-=T
source /usr/share/vim/vim73/mswin.vim
behave mswin
"for loading nerdtree
call pathogen#infect()
map <F2> :NERDTreeToggle<CR>
