
<div id="sidebar">
    <dl>
           <dt> Why we need your email? </dt>
			<dd>we need your email to  identify you on our site. We respect your privacy
			and do not display or use your email in any other way.</dd>

            <dt> What is a good password? </dt>
			<dd>A Good password should be hard to guess for people who know you.
			Do not use proper nouns or dictionary words.</dd>
    </dl>
</div>

