  <div class="well p20">
           <ul class="nav nav-list">
               <li class="nav-header"><?php echo $userDBRow['name']; ?></li>
               <li><a href="/user/dashboard/posts.php">Posts</a></li>
               <li><a href="/user/dashboard/comments.php">Comments</a></li>
               <li><a href="/user/dashboard/profile.php">Profile</a></li>
               <li><a href="/user/dashboard/bookmark.php?code=1">Likes</a></li>
               <li><a href="/user/dashboard/bookmark.php?code=2">Favorites</a></li>
            </ul>
      </div> 