<div class="tile">
    <div id="home-tile">
        <h1> 
            Discover
            <br>
            and Share
            <br>
            with 3mik 
        </h1>
        <div class="p20">
            <a class="btn" href="/user/register.php">Register</a>
            <a class="btn" href="/site/about.php">Learn More</a>
        </div>
       <div class="well">
           <ul class="nav nav-list">
               <li class="nav-header">what is on 3mik?</li>
               <li><a href="/editor/picks">Editors Pick</a></li>
               <li><a href="/surprise/me">surprise me!</a></li>
               <li><a href="/group/all.php">Browse Groups</a></li>
            </ul>
      </div> 

    </div>
</div> <!-- home tile -->

