
<div id="footer">
	<div class="f-content">
		<div id="f-menu" class="floatl">
			<ul>
				<li><a href="/share/feedback.php"> Send suggestions and feedback </a> |</li>
				<li><a href="#"> FAQ </a> </li>
			</ul>
			</div>
			<div id="social" class="floatr">
				<a class="fb" href="#Facebook"></a>
				<a class="tw" href="#Twitter"></a>
				<!-- <a class="yt" href="#YouTube"></a> -->
			</div>
			<div class="clear"></div>
		<div id="copyright"> Copyright©3mik.com  </div>
	</div>
</div>
