<div class="row">
    <div class="span8 offset1">
        <div id="top-unit">
            <div class="floatl">
                <h5 class="faded-text">3mik is the place to discover shops and products in India</h5>
            </div>
            <div class="floatr">
                <a id="nav-popup-share" class="btn b">Upload</a> 
            </div>
            <div class="clear"> </div>
        </div>
    </div>

</div>