
<div id="site-toolbar" class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a> <!-- 3bars for smaller screens -->
            <a class="brand" href="/app">Sales App<span class="beta">BETA</span> </a>

            <div class="nav-collapse">
                <ul class="nav">
                    <li> <a href="/app"><i class="icon-home"></i>&nbsp;Home</a></li>
                    <li> <a href="/app/browser/login.php">Sign in</a> </li>
                </ul>
                
            </div>

        </div>

    </div>
</div> <!-- default toolbar -->

