
<div id="sidebar">
        <dl>
           <dt> What is a good question? </dt>
			<dd>Please be specific. A focused and on the topic question has a better chance
			to get answered. </dd>

            <dt> Add Multiple images </dt>
			<dd>You can click on Add images and select multiple images from your computer</dd>

            <dt> Add link </dt>
			<dd> Write or paste link in the box and click on (+) Add next to it. 
                You can add as many links as you like.</dd>
            <dt> Groups </dt>
			<dd> Groups help you organize your posts. You can select existing groups or add a new one.</dd>
        </dl>

        </dl>

</div>

