
<div id="sidebar">
        <dl>
          
            <dt> Add Multiple images </dt>
			<dd>You can click on Add images and select multiple images from your computer</dd>

            <dt> Add link </dt>
			<dd> Write or paste link in the box and click on (+) Add next to it. 
                You can add as many links as you like.</dd>
            <dt> Tags </dt>
			<dd> Tags help you organize your posts and allows others to find your post quickly.</dd>
        </dl>

        </dl>

</div>

