  <div class="well p20">
           <ul class="nav nav-list">
               <li class="nav-header">Hello user with SuperCow Powers! </li>
               
               <li><a href="/monitor/index.php">Posts</a></li>
               <li><a href="/monitor/comments.php">Comments</a></li>
               <li><a href="/monitor/groups.php">Groups</a></li>
               <li><a href="/monitor/feedback.php">Feedback</a></li>
               <li><a href="/monitor/users.php">Users</a></li>
               
            </ul>
      </div> 