
<div id="site-toolbar" class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="/">3mik.com <span class="beta">BETA</span> </a>
            <ul class="nav">
                <li> <a href="/"><i class="icon-home"></i>&nbsp;Home</a></li> 
            </ul>
        </div>
    </div>
</div>

<div id="block-spinner"> </div>

<div id="simple-popup">
     <div id="header">
         <div class="wrapper">
            <div class="floatr">
                <a id="simple-popup-close" href="">close&nbsp;<i class="icon-remove"> </i></a>
            </div>
        </div>
        <div class="clear"> </div>
     </div>
    <div id="content"> </div>

</div>

<div id="popup-mask"> </div>
<!-- site simple popup -->

