
<div id="site-toolbar" class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="/">3mik.com <span class="beta">BETA</span> </a>
            <ul class="nav">
                <li> <a href="/"><i class="icon-home"></i>&nbsp;Home</a></li>
                 <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu<b class="caret"></b></a>
                        <ul class="dropdown-menu">

                            <li>
                               <div id="submenu-col2"> 
                                   
                                    <ul>

                                        <li><a href="/monitor/index.php">Posts</a></li>
                                        <li><a href="/monitor/comments.php">Comments</a></li>
                                        <li><a href="/monitor/feed.php">Activities</a></li>
                                    </ul>
                                     <ul>

                                        <li><a href="/monitor/users.php">Users</a></li>
                                        <li><a href="/monitor/groups.php">Groups</a></li>
                                        <li><a href="/monitor/feedback.php">Feedback</a></li>
                                    </ul>

                                </div> <!-- 2-col submenu -->
                            </li>
                        </ul>
                    </li>  <!-- user menu -->

            </ul>
        </div>
    </div>
</div>