<div id="header">
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container">
                <div class="pull-left">
                    <a class="brand" href="/">3mik.com  <span class="beta">BETA</span> </a>
                </div>
                <div class="pull-left">
                    <ul class="nav">
                        <li class="active"> <a href="/">Home</a> </li>
                    </ul> <!-- links -->
                </div>
          </div>
        </div>
    </div> <!-- navbar -->
</div> <!-- header -->
